01_MY TALK:
- content: This is an AI generated research talk showing how you can easily create
    a talk to replace the silly required videos at conferences. Simply export your
    slides as PNG, write a script, and you're golden!
  index: 1
- content: No one except a disinterested reviewer watches these anyways. Basically,
    this took me like 30 minutes to set up with my existing tooling and ChatGPT. Unfortunately,
    11labs isn't free. The perk of collaborating with me is that you can use my credits!
    Capitalism!
  index: 2
- content: The method is simple. You download your slides as a pdf, then you use imagemagic
    tool to convert to PNG, then you write your script in markdown and my texttospeech
    script does the rest. The detailed instructions are all in the readme.
  index: 3
- content: If I was a reviewer I would probably be salty about this, but really I
    should be impressed. AI students should use AI! I'm not proud or embarrassed,
    just competitive!
  index: 4
date: null
md: examples/research-talk/research-talk.md
