1_Test Post:
- content: The future of writing with AI
  index: 1
- content: the brown boy walks the cat. Adding a sentence!
  index: 2
- content:
    alt_text: "Screenshot 2023-12-22 at 10.56.47\u202FAM.png"
    path: test-post/Screenshot_2023-12-22_at_10.56.47_AM.png
  index: 3
2_Next section!:
- content: How are you doing?
  index: 4
- content: Let's have a couple paragraphs here. This one has another sentence.
  index: 5
3_Final section:
- content: Blah blah blah. Thanks for listening. Blah dog.
  index: 6
- content: I hope my new workflow works great!
  index: 7
date: December 27th 2023
md: source/test-post/test-post.md
