01_Alignment-as-a-Service upstarts taking on Scale AI:
- content: Scale's making over $750 million per year selling data for RLHF, who's
    coming to take it?
  index: 1
- content: Scale AI, the startup once known for various selfdriving and military data
    labeling contracts, is closing in on a billion of annualized revenue on its data
    services for techniques like reinforcement learning from human feedback (RLHF).
    I'd heard plenty of rumors about this, and things like them working with every
    major lab from Meta to OpenAI, but seeing some of it in public reporting feels
    different.
  index: 2
- content: Quoting from Forbes
  index: 3
- content: '> Scale''s defense arm still pales in comparison to its commercial business,
    which pushed the company''s annualized revenue run rate in late 2023 to $750 million,
    according to two people familiar with the matter -- up from about $250 million
    in early 2022.

    That growth was spurred by skyrocketing demand from Al companies for reinforcement
    learning with human feedback (RLHF), a data labeling technique for large language
    models.'
  index: 4
02_Part two:
- content: Scale's revenue mirrors the general industry sentiment towards RLHF over
    the last few years. I'm curious what the $250 million in early 2022 was, but I
    can assure lots of data budgets across the ML industry got reallocated towards
    RLHF. Doing RLHF well and making a truly sticky model takes a big investment.
  index: 5
- content: These revenue numbers aren't far off from what OpenAI is seeing and they're
    from a different direction (and a much, much lower valuation) -- paid services
    for building and maintaining models rather than serving models. While the short
    arguments on foundation model providers have been studied at length -- they focus
    on the commoditization of the services and races to the bottom -- it's useful
    to study Scale, predict where they're making their money, and understand where
    the upstarts will try and jump in.
  index: 6
date: null
md: examples/experimental/experimental.md
